country_continent_mapping = {
    "United Kingdom": "Europe",
    "France": "Europe", 
    "Australia": "Oceania",
    "Netherlands": "Europe", 
    "Germany": "Europe", 
    "Norway": "Europe",
    "EIRE": "Europe", 
    "Switzerland": "Europe", 
    "Spain": "Europe",
    "Poland": "Europe", 
    "Portugal": "Europe", 
    "Italy": "Europe",
    "Belgium": "Europe", 
    "Lithuania": "Europe", 
    "Japan": "Asia",
    "Iceland": "Europe", 
    "Channel Islands": "Europe", 
    "Denmark": "Europe",
    "Cyprus": "Europe",
    "Sweden": "Europe", 
    "Finland": "Europe",
    "Austria": "Europe",
    "Greece": "Europe", 
    "Singapore": "Asia",
    "Lebanon": "Asia", 
    "United Arab Emirates": "Asia", 
    "Israel": "Asia",
    "Saudi Arabia": "Asia",
    "Czech Republic": "Europe", 
    "Canada": "North America",
    "Unspecified": "Unknown", 
    "Brazil": "South America", 
    "USA": "North America",
    "European Community": "Europe", 
    "Bahrain": "Asia", 
    "Malta": "Europe", 
    "RSA": "Africa"
}
    